### ISSUE TITLE
Any user guide code about restrict_policies

### ISSUE THREAD

**Issue by liumilan** [tensorflow/recommenders-addons#113]
I'd like to use tfra.dynamic_embedding.FrequencyRestrictPolicy or tfra.dynamic_embedding.TimestampRestrictPolicy ,could u help to offer some example codes about how to using these two api.And the other question is that it need to specify the num_reserved in this apis,what means the model will always the same number of parameters?

**Comment by Lifann** [comment]
Hi, @liumilan . Nice to have your ask. I'm currently working on a tutorial  for showing how to use the `RestrictPolicy`s in trainng. we also have Some example code [here](https://github.com/tensorflow/recommenders-addons/blob/master/tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py#L1124-L1256) which may help you. And integrated, end-to-end demo will be published soon.

**Comment by Lifann** [comment]
I'm not sure I fully understand the meaning of "always the same number of parameters". `num_reserved` is the number of kv pairs left after the restriction ([docs](https://github.com/tensorflow/recommenders-addons/blob/master/docs/api_docs/tfra/dynamic_embedding/RestrictPolicy.md)).

**Comment by liumilan** [comment]
> Hi, @liumilan . Nice to have your ask. I'm currently working on a tutorial for showing how to use the `RestrictPolicy`s in trainng. we also have some example code [here](https://github.com/tensorflow/recommenders-addons/blob/master/tensorflow_recommenders_addons/dy 
 namic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py#L1124-L1256) which may help you. And integrated, end-to-end demo will be published soon.

**Comment by liumilan** [comment]
> I'm not sure I fully understand the meaning of "always the same number of parameters". `num_reserved` is the number of kv pairs left after the restriction ([docs](https://github.com/tensorflow/recommenders-addons/blob/master/docs/api_docs/tfra/dynamic_embedding/RestrictPolicy.md)).

Because the model will be updated hour by hour.If this parameter is specified, the model size will be kept stable?

**Comment by liumilan** [comment]
> here



> Hi, @liumilan . Nice to have your ask. I'm currently working on a tutorial for showing how to use the `RestrictPolicy`s in trainng. we also have some example code [here](https://github.com/tensorflow/recommenders-addons/blob/master/tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py#L1124-L1256) which may help you. And integrated, end-to-end demo will be published soon.

from your examle codes , i can't find  how to use apply_update api codes. And shall i use these two policy simultaneously？ How long will it take to publish ?

**Comment by Lifann** [comment]
> > here
> 
> > Hi, @liumilan . Nice to have your ask. I'm currently working on a tutorial for showing how to use the `RestrictPolicy`s in trainng. we also have some example code [here](https://github.com/tensorflow/recommenders-addons/blob/master/tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py#L1124-L1256) which may help you. And integrated, end-to-end demo will be published soon.
> 
> from your examle codes , i can't find how to use apply_update api codes. And shall i use these two policy simultaneously？ How long will it take to publish ?

When you call `dynamic_embedding.Variable.restrict`, the sparse parameter size is reduced to `num_reserved`.
```python
    var_guard_by_tstp.restrict(num_reserved, trigger=trigger)
    var_guard_by_freq.restrict(num_reserved, trigger=trigger)
    var_sizes = [spv.size() for spv in sparse_vars]
    self.assertAllEqual(var_sizes, [num_reserved, num_reserved])
```
If you need a more complex policy, I suggest implementing a new policy class inherit the `RestrictPolicy`.
And every Variable only takes one policy when created.
