### ISSUE TITLE
EmbeddingVariable support shard

### ISSUE THREAD

**Issue by wangcaihua** [tensorflow/recommenders-addons#124]
**The recommendation models are usually very big, say 1T. So the single embedding variable is too small to hold so much parameters. It's a good idea to extend embedding variable to partitioned variable**

https://github.com/tensorflow/recommenders-addons/blob/master/tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable_ops.py

**Relevant information**
- Are you willing to contribute it (no):
- Are you willing to maintain it going forward? (yes):
- Is there a relevant academic paper? (no, but the tf code itself can saver as a good example):
- Is there already an implementation in another framework? (no):
- Was it part of tf.contrib? (no, just in TFRA):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**
The community users will do benefit from it. 

**Any other info.**

**Comment by qqsun8819** [comment]
I'm working on this. @liutongxuan  assign this to me
