### ISSUE TITLE
Problem with MirroredStrategy (Single Machine Multi GPU) on demo/movielens-100k-estimator

### ISSUE THREAD

**Issue by ivanml** [tensorflow/recommenders-addons#135]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
  - CentOS 7
- TensorFlow version and how it was installed (source or binary): 
  - $ pip list | grep tensorflow
tensorflow                     2.4.1
tensorflow-addons              0.13.0
tensorflow-datasets            4.4.0
tensorflow-estimator           2.4.0
tensorflow-gpu                 2.4.1
tensorflow-metadata            1.2.0
tensorflow-recommenders-addons 0.2.0
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary):
  - see above
- Python version:
  - Python 3.6.8
- Is GPU used? (yes/no):
  yes

**Describe the bug**
Hi,

I was able to run the demo (demo/movielens-100k-estimator) as it is, with no distributed strategy.

However when I have tried to make it compatible with `tf.distribute.MirroredStrategy()` on GPU, I was not able to run through the program.

**Code to reproduce the issue**
Only 3 places I have changed within the code:
- the loss function (in func `def model_fn()`):
```
loss_obj = tf.keras.losses.MeanSquaredError(reduction=tf.keras.losses.Reduction.NONE)
loss = tf.reduce_sum(loss_obj(labels, predictions)) * (1. / GLOBAL_BATCH_SIZE)
# GLOBAL_BATCH_SIZE = 256
```
- adding the distribute strategy in Estimator run_config (in func `def train(model_dir, ps_num)`):
```
def train(model_dir, ps_num):
  mirrored_strategy = tf.distribute.MirroredStrategy()
  run_config = tf.estimator.RunConfig(log_step_count_steps=100,
                                      save_summary_steps=100,
                                      save_checkpoints_steps=100,
                                      save_checkpoints_secs=None,
                                      keep_checkpoint_max=2,
                                      train_distribute=mirrored_strategy,
                                      eval_distribute=mirrored_strategy)
```
- I removed the TF_CONFIG settings in main as it is not need in MirroredStrategy

Log shows error in Add_N op with dimension mismatch:
(from personal debugging process I guess the problem is at optimizer apply gradients)
```
.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 64 and 256. Shapes are [64,256] and [256,64].
        From merging shape 0 with other shapes. for '{{node AddN_2}} = AddN[N=2, T=DT_FLOAT](gradients/dense/MatMul_grad/tuple/control_dependency_1, replica_1/gradients/replica_1/dense_4/MatMul_grad/tuple/control_dependency_1)' with input shapes: [64,256], [256,64].
```

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ivanml** [comment]
can anyone take a look? @rhdong  @Lifann

**Comment by rhdong** [comment]
Hi @ivanml,  I believe the Dynamic Embedding can't support MirroredStrategy for different size of IDs in different work, you know, different batch can contain different number of features, isn't it?

**Comment by MoFHeka** [comment]
Mirrored Strategy is now supported in TF2 Keras. But it has some performance problem, which cause by lacking of all-to-all communication operator.

**Comment by MoFHeka** [comment]
This issue is solved for the time being, I will close this issue. Turn it back on if necessary.
