### ISSUE TITLE
dynamic_embedding does not return the same embeddings for the same id

### ISSUE THREAD

**Issue by Chengtianxiang** [tensorflow/recommenders-addons#136]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.5
- TensorFlow version and how it was installed (source or binary): 2.4.1 in docker
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): 0.2.0 use pip
- Python version: 3.6.9
- Is GPU used? (yes/no): no

**Describe the bug**

dynamic_embedding.embedding_lookup does not return the same embeddings for the same id.

```python
import tensorflow as tf
import tensorflow_recommenders_addons as tfra
x = tf.constant([1, 2, 3], dtype=tf.int64)
embedding_dict = tfra.dynamic_embedding.get_variable(
    name="x_embeddings", 
    dim=3, 
    initializer=tf.keras.initializers.RandomNormal(-1, 1))

print(tfra.dynamic_embedding.embedding_lookup(
    params=embedding_dict,
    ids=x,
    name="x_embedding"))
print(tfra.dynamic_embedding.embedding_lookup(
    params=embedding_dict,
    ids=x,
    name="x_embedding"))
```

result is:

>`tf.Tensor(
[[-0.6480133 -1.7569897 -1.7143806]
 [ 0.9366411  0.2751621 -2.882576 ]
 [-3.657474  -0.5267197 -1.1529406]], shape=(3, 3), dtype=float32)`
`tf.Tensor(
[[-0.48164272 -0.32765645 -2.0944896 ]
 [-1.5339627  -1.8370364   0.68307126]
 [-0.36742425  0.06579518 -0.31739855]], shape=(3, 3), dtype=float32)`

I also tried EmbeddingVariable in the same manner, it works fine.

So what's the problem when I use dynamic_embedding? 

Thanks for your help

**Comment by hxfxjun** [comment]
dynamic_embedding好像每次在lookup时如果key不存在，会用initializer去初始化default值，因为你是RandomNormal的，所以每次都不一样

**Comment by Chengtianxiang** [comment]
> dynamic_embedding好像每次在lookup时如果key不存在，会用initializer去初始化default值，因为你是RandomNormal的，所以每次都不一样

这个没问题，但是我是对同一个输入做了两次lookup，结果不一致

**Comment by hxfxjun** [comment]
> > dynamic_embedding好像每次在lookup时如果key不存在，会用initializer去初始化default值，因为你是RandomNormal的，所以每次都不一样
> 
> 这个没问题，但是我是对同一个输入做了两次lookup，结果不一致

每次lookup后，并没有把default做insert操作，所以每次都是随机的

**Comment by rhdong** [comment]
> > > dynamic_embedding好像每次在lookup时如果key不存在，会用initializer去初始化default值，因为你是RandomNormal的，所以每次都不一样
> > 
> > 
> > 这个没问题，但是我是对同一个输入做了两次lookup，结果不一致
> 
> 每次lookup后，并没有把default做insert操作，所以每次都是随机的

Yes, lookup is const function, we believe it should not change any thing in the variable, so we keep id missing.
Plz @Chengtianxiang refer to this explaination.

**Comment by Chengtianxiang** [comment]
> > > > dynamic_embedding好像每次在lookup时如果key不存在，会用initializer去初始化default值，因为你是RandomNormal的，所以每次都不一样
> > > 
> > > 
> > > 这个没问题，但是我是对同一个输入做了两次lookup，结果不一致
> > 
> > 
> > 每次lookup后，并没有把default做insert操作，所以每次都是随机的
> 
> Yes, lookup is const function, we believe it should not change any thing in the variable, so we keep id missing.
> Plz @Chengtianxiang refer to this explaination.

OK，got it. But how to make the code above right?
