### ISSUE TITLE
2021-08-25T15:28:56.666 session_manager.py 436 INFO Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: deep_scope/embedding/item_deep/vector, deep_scope/embedding/cid_deep/vector, deep_scope/embedding/actor_deep/vector, ready: None

### ISSUE THREAD

**Issue by hxfxjun** [tensorflow/recommenders-addons#143]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18
- TensorFlow version and how it was installed (source or binary): 1.15.2
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): source
- Python version:3.6.9
- Is GPU used? (yes/no):no

**Describe the bug**

chief is normal, but worker is doesn't work
2021-08-25T15:28:56.666 session_manager.py 436 INFO Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: deep_scope/embedding/item_deep/vector, deep_scope/embedding/cid_deep/vector, deep_scope/embedding/actor_deep/vector, ready: None

**Code to reproduce the issue**

            deep_emb = tfra.embedding_variable.EmbeddingVariable(
                name=deep_scope,
                ktype=tf.int32,
                embedding_dim=emb_dim,
                initializer=tf.keras.initializers.Zeros())

           opt = tf.train.AdagradOptimizer(lr, use_locking=True)

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by qqsun8819** [comment]
is this issue same as #146 ? @hxfxjun

**Comment by hxfxjun** [comment]
> is this issue same as #146 ? @hxfxjun

yes
