### ISSUE TITLE
ev example改为多个worker后，只有worker0可以训练，其它worker一直在等待初始化无法训练

### ISSUE THREAD

**Issue by hxfxjun** [tensorflow/recommenders-addons#146]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version and how it was installed (source or binary):
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary):
- Python version:
- Is GPU used? (yes/no):

python ev-norm-ps.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100,127.0.0.1:9101 --task_index=0 --job_name=ps
python ev-norm-ps.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100,127.0.0.1:9101 --task_index=0 --job_name=worker
python ev-norm-ps.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100,127.0.0.1:9101 --task_index=1 --job_name=worker

INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: var_dist, var_dist/Adagrad/EmbeddingVariable, ready: None
I0827 15:12:00.834718 4358843904 session_manager.py:436] Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: var_dist, var_dist/Adagrad/EmbeddingVariable, ready: None

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
@liutongxuan

**Comment by qqsun8819** [comment]
I'll check this
