### ISSUE TITLE
Ev can support FTRL optimizer?

### ISSUE THREAD

**Issue by hxfxjun** [tensorflow/recommenders-addons#147]
**Describe the feature and the current behavior/state.**

 Ev can support FTRL optimizer?

**Relevant information**
- Are you willing to contribute it (yes/no):no
- Are you willing to maintain it going forward? (yes/no):yes
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**

**Any other info.**

**Comment by rhdong** [comment]
Hi @hxfxjun, I'm sorry for a long time no reply, and maybe you can try `tfra.dynamic_embedding`, which is compatible with all optimizers of TensorFlow. I'll close this issue; please feel free to reopen it if any help is needed; thank you ~
