### ISSUE TITLE
can not load file "_ev_ops.so" on TF1.15.2

### ISSUE THREAD

**Issue by canisn** [tensorflow/recommenders-addons#173]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Darwin MacBookPro 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- TensorFlow version and how it was installed (source or binary):
tf  1.15.2 install in conda by pip install
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary):
tfra   0.2.0 install in conda by pip install
- Python version:
3.6.9
- Is GPU used? (yes/no):
no
**Describe the bug**
when install tfra，tf will auto update to 2.4.1，but tf1.0 was used in my code, so I reinstall tf to 1.15.2
then I run demo with tfra.ev，error raise when tfra init

Traceback (most recent call last):
  File "/path/ev.py", line 5, in <module>
    import tensorflow_recommenders_addons as tfra
  File "/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/__init__.py", line 31, in <module>
    from tensorflow_recommenders_addons import embedding_variable
  File "/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/__init__.py", line 1, in <module>
    from tensorflow_recommenders_addons.embedding_variable.python.ops.embedding_variable_ops import *
  File "/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/python/__init__.py", line 55, in <module>
    gen_ev_ops = _load_library("../core/_ev_ops.so")
  File "/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/python/__init__.py", line 52, in _load_library
    "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs))
NotImplementedError: unable to open file: ../core/_ev_ops.so, from paths: ['/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/python/../core/_ev_ops.so']
caused by: ['dlopen(/path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/python/../core/_ev_ops.so, 6): Library not loaded: @rpath/libtensorflow_framework.2.dylib\n  Referenced from: /path/py3/lib/python3.6/site-packages/tensorflow_recommenders_addons/embedding_variable/core/_ev_ops.so\n  Reason: image not found']

**Code to reproduce the issue**
import tensorflow_recommenders_addons as tfra

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rhdong** [comment]
Hi @qqsun8819, any help?
