### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by lwmonster** [tensorflow/recommenders-addons#186]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): tensorflow 1.15.0 installed by pip
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): can't install 
- Python version: 2.7.12
- Is GPU used? (yes/no):no

install log: 
ERROR: Could not find a version that satisfies the requirement tensorflow-recommenders-addons (from versions: none)
ERROR: No matching distribution found for tensorflow-recommenders-addons

**Comment by rhdong** [comment]
@lwmonster Hi, TFRA is not supported in python2.x environment. Maybe you can update python to 3.6 or later version. Thank you!
