### ISSUE TITLE
Confusion about “dynamic embedding” remove operation

### ISSUE THREAD

**Issue by MuYu-zhi** [tensorflow/recommenders-addons#193]
Appreciate some explanation about hash conflict in remove operation. I wonder about a situation like this, if two features are mapped to the same embedding vector, when I remove one of them, the corresponding embedding vector would be cleared (as I understand), what would happen when the other feature looks up the embedding table again, would it be treated as a new feature and with a new embedding vector inserted?

**Comment by Lifann** [comment]
Hi, @JinrongGuo1 . There is no hash confliction in `dynamic_embedding`.

**Comment by MuYu-zhi** [comment]
Thanks, I got it.
