### ISSUE TITLE
Any plan to support TF=1.15 and CUDA=11.1?

### ISSUE THREAD

**Issue by karterotte** [tensorflow/recommenders-addons#195]
**Describe the feature and the current behavior/state.**
Now tfra works on tf=1.15 and cuda =10 in gpu supporting.
I want to use it in  nvidia 3090 gpu. In TF<2.0 AND gpu card needs cuda >=11.0. 
Do you have any plan to compile a version to support this condition?
**Relevant information**
- Are you willing to contribute it (yes/no):
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**
etc
**Who will benefit with this feature?**
Many companies who use tf 1 and 3090 gpu.
**Any other info.**

**Comment by rhdong** [comment]
Hi @karterotte ,thank you for your feedback, but unfortunately, we have no plan to support TF1.15+CUDA11.1, for official TF1.15 requires CUDA10.0,  TFRA following this. We recommend you update TF version to 2.5.1 , or maybe you can seek resolution from [NVIDIA GPU CLOUD](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow/tags), there're some custom TF1.15 with different CUDA version, and then compiling the TFRA from resource back the NVIDIA custom TF release.
