### ISSUE TITLE
请问 我使用python3 读取redis内存储的embedding 是乱码（不依赖tfra库读，而是使用redis的python包） python无法解析   

### ISSUE THREAD

**Issue by oldlee11** [tensorflow/recommenders-addons#246]
**Describe the feature and the current behavior/state.**

**Relevant information**
- Are you willing to contribute it (yes/no):
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**

**Any other info.**

**Comment by rhdong** [comment]
I think this is not a TFRA issue. Maybe you can commit a issue to redis community? thank you~
