### ISSUE TITLE
how to initialize emb table with pretrained item/user embeddings

### ISSUE THREAD

**Issue by tonight-is-you** [tensorflow/recommenders-addons#247]
**Describe the feature and the current behavior/state.**
i see dynamic_embedding.get_variable() has a initializer parameter, but it used for missing key in the hash table, now i have item embeddings generated by pretrained nlp model like bert, i want to use this embeddings for initialization, how can i do this?

**Comment by rhdong** [comment]
Hi @tonight-is-you, you can use the [`upsert`](https://github.com/tensorflow/recommenders-addons/blob/master/docs/api_docs/tfra/dynamic_embedding/Variable.md#upsert) API import the pre-trained embedding before training loop starting.
