### ISSUE TITLE
How to install tensorflow-recommenders-addons package?

### ISSUE THREAD

**Issue by zuston** [tensorflow/recommenders-addons#26]
In pypi, i can't find tensorflow-recommenders-addons package.
But in README, it indicated that I can install this project from pypi.
It makes me confused.

Now, the only solution is to build code to use?

**Comment by rhdong** [comment]
Hi @zuston , thank you for your attention, TFRA is still on phrase of initial development, and we plan to publish the 1st release version within a week.

**Comment by zuston** [comment]
looking forward it!

**Comment by chiangqiqi** [comment]
Hi, @rhdong , I try to build this addon using bazel, after build, encounter with this error

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-c9de7556993b> in <module>
----> 1 import tensorflow_recommenders_addons as tfra

tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/__init__.py in <module>
     26 __version__ = "v0.1.0"
     27
---> 28 from tensorflow_recommenders_addons import dynamic_embedding
     29 from tensorflow_recommenders_addons import embedding_variable
     30 from tensorflow_recommenders_addons.register import register_all

tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/__init__.py in <module>
     15 """Export dynamic_embedding APIs."""
     16
---> 17 from tensorflow_recommenders_addons.dynamic_embedding.python.ops.cuckoo_hashtable_ops import (
     18     CuckooHashTable,)
     19 from tensorflow_recommenders_addons.dynamic_embedding.python.ops.dynamic_embedding_optimizer import (

tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py in <module>
     28 from tensorflow_recommenders_addons.utils.resource_loader import LazySO
     29
---> 30 cuckoo_hashtable_ops = LazySO(
     31     "dynamic_embedding/core/_cuckoo_hashtable_ops.so").ops
     32

tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/utils/resource_loader.py in ops(self)
     61     if self._ops is None:
     62       self.display_warning_if_incompatible()
---> 63       self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
     64     return self._ops
     65

tf-gpu2/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     55     RuntimeError: when unable to load the library or get the python wrappers.
     56   """
---> 57   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     58   try:
     59     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/core/_cuckoo_hashtable_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

do you guys know how to deal with this issue?

**Comment by rhdong** [comment]
> Hi, @rhdong , I try to build this addon using bazel, after build, encounter with this error
> 
> ```
> ---------------------------------------------------------------------------
> NotFoundError                             Traceback (most recent call last)
> <ipython-input-2-c9de7556993b> in <module>
> ----> 1 import tensorflow_recommenders_addons as tfra
> 
> tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/__init__.py in <module>
>      26 __version__ = "v0.1.0"
>      27
> ---> 28 from tensorflow_recommenders_addons import dynamic_embedding
>      29 from tensorflow_recommenders_addons import embedding_variable
>      30 from tensorflow_recommenders_addons.register import register_all
> 
> tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/__init__.py in <module>
>      15 """Export dynamic_embedding APIs."""
>      16
> ---> 17 from tensorflow_recommenders_addons.dynamic_embedding.python.ops.cuckoo_hashtable_ops import (
>      18     CuckooHashTable,)
>      19 from tensorflow_recommenders_addons.dynamic_embedding.python.ops.dynamic_embedding_optimizer import (
> 
> tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py in <module>
>      28 from tensorflow_recommenders_addons.utils.resource_loader import LazySO
>      29
> ---> 30 cuckoo_hashtable_ops = LazySO(
>      31     "dynamic_embedding/core/_cuckoo_hashtable_ops.so").ops
>      32
> 
> tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/utils/resource_loader.py in ops(self)
>      61     if self._ops is None:
>      62       self.display_warning_if_incompatible()
> ---> 63       self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
>      64     return self._ops
>      65
> 
> tf-gpu2/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
>      55     RuntimeError: when unable to load the library or get the python wrappers.
>      56   """
> ---> 57   lib_handle = py_tf.TF_LoadLibrary(library_filename)
>      58   try:
>      59     wrappers = _pywrap_python_op_gen.GetPythonWrappers(
> 
> NotFoundError: tf-gpu2/lib/python3.8/site-packages/tensorflow_recommenders_addons/dynamic_embedding/core/_cuckoo_hashtable_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
> ```
> 
> do you guys know how to deal with this issue?

We published the first release version 7 hours ago , you can try again on the r0.1 branches.
And maybe you'd better follow the building guide on the README.md and confirm you have install TF2.x version. on the building env. Thx!

**Comment by rhdong** [comment]
> looking forward it!
Hi @zuston , the first release has been published, plz check it, thx !
pip install tensorflow-recommenders-addons
