### ISSUE TITLE
How to export the model and visualize the model?

### ISSUE THREAD

**Issue by likunlin99** [tensorflow/recommenders-addons#265]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary):Tensorflow=2.5.1
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary):TensorFlow-Recommenders-Addons=0.4.0
- Python version:3.8
- Is GPU used? (yes/no):yes

**Describe the bug**

How do I export the model after I run the code？

Both export_dir and model_dir return an error

**Code to reproduce the issue**
saved_model_cli show --dir ./export_dir/ --all
saved_model_cli show --dir ./model_dir/ --all

KeyError: 'TFRA>CuckooHashTableImport'

**Other info / logs**

**Comment by MoFHeka** [comment]
@likunlin99
This issue is solved for the time being, I will close this issue. Turn it back on if necessary.
