### ISSUE TITLE
bfloat16 value type support

### ISSUE THREAD

**Issue by xiangzez** [tensorflow/recommenders-addons#266]
TFRA supports many value types including float16, but bfloat16 type is not there. Are there any specific reasons?

I tried to add a BF16 value type kernel for cuckoo hashtable op and it seems to work. And it is easier to converge than FP16 in training.

**Comment by rhdong** [comment]
Thank you @xiangzez , there're no specific reasons, you can commit a PR for this, thank you~

**Comment by rhdong** [comment]
@xiangzez 
Additionally, at the beginning, we can't confirm if it works well that TF supports bf16 on CPUs, so we didn't open the data type for bf16. Since you have already made enough testing, I believe we can try to open it, could you commit a PR?

**Comment by xiangzez** [comment]
Yes TF now supports bf16 well on CPU. I'll submit a PR for this.
