### ISSUE TITLE
TF2 : AttributeError: module 'keras' has no attribute 'initializers'

### ISSUE THREAD

**Issue by songyaheng** [tensorflow/recommenders-addons#270]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Mac
- TensorFlow version and how it was installed (source or binary): 2.5.1
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): 0.4.0
- Python version: 3.9
- Is GPU used? (yes/no): no

**Describe the bug**

Traceback (most recent call last):
  File "de_demo.py", line 5, in <module>
    import tensorflow_recommenders_addons as tfra
  File "python3.9/site-packages/tensorflow_recommenders_addons/__init__.py", line 29, in <module>
    from tensorflow_recommenders_addons import dynamic_embedding
  File "python3.9/site-packages/tensorflow_recommenders_addons/dynamic_embedding/__init__.py", line 93, in <module>
    from tensorflow_recommenders_addons.dynamic_embedding.python.ops.tf_patch import (
  File "python3.9/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py", line 39, in <module>
    kinit_K = K.initializers
AttributeError: module 'keras' has no attribute 'initializers'

**Code to reproduce the issue**

`try:
  import keras as K
  kinit_K = K.initializers
except ImportError:
  kinit_K = None
  pass  # for compatible with standalone Keras`

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rhdong** [comment]
Hi @songyaheng , we confirm this issue has been resolved in the latest version, pls check it and feel free to reopen it when needed. https://github.com/tensorflow/recommenders-addons/releases/tag/v0.5.0
