### ISSUE TITLE
Can you show in detail how to set up the development environment?

### ISSUE THREAD

**Issue by GH1995** [tensorflow/recommenders-addons#273]
可否出详细讲述如何搭建开发环境？仅靠 README.md 和 https://hub.docker.com/r/tfra/dev_container/tags 无法打包开发环境
@rhdong

**Comment by rhdong** [comment]
Hi @GH1995 , thank you for your feedback, I will check the container, and could you please provide more log info when you pack TFRA? thank you again!

**Comment by rhdong** [comment]
Hi @GH1995 , I just updated the dev container for pip error, could you try it again? Thank you so much!

**Comment by GH1995** [comment]
我执行的命令是 `bash tools/run_cpu_tests.sh`，得到的报错信息如下

```
#1 [internal] load build definition from cpu_tests.Dockerfile
#1 sha256:3b0473a5ca8839de863963ebad8a1bbbef3b4405cec2eb2e0d785b4dd4581531
#1 transferring dockerfile: 47B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:365baab47f1d289328df4d545597e6e514cdfae2b830bbc52c895062e5d471f6
#2 transferring context: 34B done
#2 DONE 0.0s

#3 resolve image config for docker.io/docker/dockerfile:1.1.5-experimental
#3 sha256:4d904ca4dadcfe285b7e07c14c496e2212a754f0c4fd12946baa040350cae4f0
#3 DONE 0.0s

#4 docker-image://docker.io/docker/dockerfile:1.1.5-experimental
#4 sha256:35df37634fe7c9fc0e5af5102f89293b3cf5b09745ed8df68e4eb661b5a7b915
#4 CACHED

#5 [internal] load metadata for docker.io/library/python:3.7
#5 sha256:2e83735093f2e645c7660e349795ae80186113afc054af8bdc7501e99da12131
#5 DONE 0.0s

#6 [build_wheel 1/21] FROM docker.io/library/python:3.7
#6 sha256:d7e6c383a204ad229f1de34acc46b7a4fa96e4e2006370caf5c4ee33014f7572
#6 DONE 0.0s

#7 [internal] load build context
#7 sha256:dd0ec923c7ff34e475b100538aaddd1b6fc6a0845ad8ae6dcfd6d5466d8e36fe
#7 transferring context: 48.96kB 0.1s done
#7 DONE 0.1s

#8 [stage-1 2/7] COPY tools/install_deps/tensorflow-cpu.txt ./
#8 sha256:135ef56da15915f1fea5a406d0260b67346b44aadf606da7f989efa60733d71e
#8 CACHED

#9 [stage-1 3/7] RUN pip install --default-timeout=1000 --upgrade --force-reinstall -r tensorflow-cpu.txt
#9 sha256:8ef5ab1c5e90069025ac309475895d00f4b9b541fd6a80317295f2321981433c
#9 CACHED

#24 [build_wheel 16/21] RUN python configure.py
#24 sha256:bf12ca85e9942694bd23e8da117ea97e495067923df62c38b775f8eecdedd1b5
#24 CACHED

#20 [build_wheel 12/21] RUN pip install -r pytest.txt pytest-cov
#20 sha256:06a03b12b7c77cc9bcc404c26038f8653c42642861e994bb46301cc41ac4b79e
#20 CACHED

#13 [build_wheel 5/21] COPY tools/docker/install/install_bazel.sh /install/
#13 sha256:7c51be9cb31e2b947969acc431cff986bbc4e8ef9a925565c6b6d7a07f7af9fc
#13 CACHED

#11 [build_wheel 3/21] RUN python -m pip install --upgrade protobuf==3.20.0
#11 sha256:e03132164318951c06df7514b7a95929387e5178c7aa5395ab245c313a08d9d0
#11 CACHED

#23 [build_wheel 15/21] RUN python -m pip install --upgrade protobuf==3.20.0
#23 sha256:0f1971225c35cb69134598e9fc8c1d83cdb63d7c4fa508fba31102e9149e6920
#23 CACHED

#17 [build_wheel 9/21] COPY requirements.txt ./
#17 sha256:a67c86713993538ceb72172d2120c9cfa34f1e039b36828018dc7049b0876de0
#17 CACHED

#19 [build_wheel 11/21] COPY tools/install_deps/pytest.txt ./
#19 sha256:ae168d1e818c31b4b43d0af4980f329776dca5c943c26782d805bde26bd07aa5
#19 CACHED

#21 [build_wheel 13/21] COPY ./ /recommenders-addons
#21 sha256:59ed814d2cd2bebad2830d17eba71b6fa3d9a038f890e1924dd9b730b2b8590d
#21 CACHED

#15 [build_wheel 7/21] COPY tools/docker/install/install_horovod.sh /install/
#15 sha256:557716a06c281cb44a8b43793d374825a009b5331dda968c1309d8a3925249cc
#15 CACHED

#14 [build_wheel 6/21] RUN  /install/install_bazel.sh 5.1.1
#14 sha256:de2bd374f0f7118287fa1bf3c1ebfad61cf430ef00f664352dfcb694d145213b
#14 CACHED

#16 [build_wheel 8/21] RUN  /install/install_horovod.sh 0.23.0 --only-cpu
#16 sha256:ff0d3f7ddd88cc6fc30c4408a76ef8d49e3e6b67b3f272e69a798d3e6c3e3049
#16 CACHED

#12 [build_wheel 4/21] RUN apt-get update && apt-get install -y sudo rsync cmake openmpi-bin libopenmpi-dev
#12 sha256:e5acfac271796b09ffb6c8783bcc380a5f3a1442abb021b0297d2c4d306d7aa5
#12 CACHED

#22 [build_wheel 14/21] WORKDIR recommenders-addons
#22 sha256:75068cf58e9807f8c74d0ae05f595cb296699fc4dded50a9d793c55f9dedc310
#22 CACHED

#18 [build_wheel 10/21] RUN pip install -r requirements.txt
#18 sha256:a17cb5fab16567fb2238f47aea089ffb0ed71fcc3090b27ad6f1c9a59417541f
#18 CACHED

#10 [build_wheel 2/21] RUN pip install --default-timeout=1000 tensorflow-cpu==2.5.1
#10 sha256:c95cb8cc3d3ef1fde7840d01c58311d00d38527074474c48d31cd380c4f3e992
#10 CACHED

#25 [build_wheel 17/21] RUN pip install -e ./
#25 sha256:09fb1ffeeb84c76581a9ddb0a613fcc9916875bb9b6e4c12df47ebf2e179c8fd
#25 CACHED

#26 [build_wheel 18/21] RUN --mount=type=cache,id=cache_bazel,target=/root/.cache/bazel     bash tools/install_so_files.sh
#26 sha256:25c13fd8882b9cab40f4bba5be6803abfe14cc967ad5faa18d65a3de3cb8f635
#26 0.237 + bazel build --local_ram_resources=4096 --cxxopt=-w --copt=-w //tensorflow_recommenders_addons/...
#26 0.293 Starting local Bazel server and connecting to it...
#26 3.291 Loading:
#26 3.299 Loading: 0 packages loaded
#26 4.287 Analyzing: 25 targets (12 packages loaded, 0 targets configured)
#26 5.315 Analyzing: 25 targets (67 packages loaded, 582 targets configured)
#26 5.366 WARNING: /root/.cache/bazel/_bazel_root/614b76bd6043cd177ba2f8b6681646ef/external/local_config_tf/BUILD:12657:8: target 'libtensorflow_framework.so.2' is both a rule and a file; please choose another name for the rule
#26 6.311 Analyzing: 25 targets (77 packages loaded, 8195 targets configured)
#26 6.734 INFO: Analyzed 25 targets (77 packages loaded, 8309 targets configured).
#26 6.739 INFO: Found 25 targets...
#26 6.981 [1 / 7] [Prepa] BazelWorkspaceStatusAction stable-status.txt
#26 8.312 [14 / 23] checking cached actions
#26 10.65 [20 / 60] [Prepa] Foreign Cc - CMake: Building hiredis
#26 12.46 [63 / 112] Foreign Cc - CMake: Building hiredis; 1s local ... (4 actions running)
#26 13.87 [63 / 112] Foreign Cc - CMake: Building hiredis; 3s local ... (4 actions running)
#26 18.70 [64 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 7s local ... (4 actions, 3 running)
#26 21.09 [65 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 9s local ... (4 actions running)
#26 26.48 [66 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 14s local ... (4 actions, 3 running)
#26 30.03 [66 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 18s local ... (4 actions running)
#26 34.07 [67 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 22s local ... (4 actions, 3 running)
#26 41.49 [68 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 29s local ... (4 actions, 3 running)
#26 48.53 [68 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 36s local ... (4 actions running)
#26 55.36 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 43s local ... (4 actions running)
#26 63.64 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 51s local ... (4 actions running)
#26 91.24 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 79s local ... (4 actions running)
#26 91.37 ERROR: /recommenders-addons/tensorflow_recommenders_addons/dynamic_embedding/core/BUILD:11:18: Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 48 arguments skipped)
#26 91.38 gcc: fatal error: Killed signal terminated program cc1plus
#26 91.38 compilation terminated.
#26 93.35 INFO: Elapsed time: 92.407s, Critical Path: 84.88s
#26 93.36 INFO: 12 processes: 5 internal, 7 local.
#26 93.36 FAILED: Build did NOT complete successfully
#26 93.46 FAILED: Build did NOT complete successfully
#26 ERROR: executor failed running [/bin/sh -c bash tools/install_so_files.sh]: exit code: 1
------
 > [build_wheel 18/21] RUN --mount=type=cache,id=cache_bazel,target=/root/.cache/bazel     bash tools/install_so_files.sh:
------
executor failed running [/bin/sh -c bash tools/install_so_files.sh]: exit code: 1
```

**Comment by rhdong** [comment]
> @rhdong
> 
> 我执行的命令是 `bash tools/run_cpu_tests.sh`，得到的报错信息如下
> 
> 系统信息，mac+intel commit_id: [64af57b](https://github.com/tensorflow/recommenders-addons/commit/64af57b84ab1b73500d264a5427f65c98c9993a9)
> 
> ```
> #1 [internal] load build definition from cpu_tests.Dockerfile
> #1 sha256:3b0473a5ca8839de863963ebad8a1bbbef3b4405cec2eb2e0d785b4dd4581531
> #1 transferring dockerfile: 47B done
> #1 DONE 0.0s
> 
> #2 [internal] load .dockerignore
> #2 sha256:365baab47f1d289328df4d545597e6e514cdfae2b830bbc52c895062e5d471f6
> #2 transferring context: 34B done
> #2 DONE 0.0s
> 
> #3 resolve image config for docker.io/docker/dockerfile:1.1.5-experimental
> #3 sha256:4d904ca4dadcfe285b7e07c14c496e2212a754f0c4fd12946baa040350cae4f0
> #3 DONE 0.0s
> 
> #4 docker-image://docker.io/docker/dockerfile:1.1.5-experimental
> #4 sha256:35df37634fe7c9fc0e5af5102f89293b3cf5b09745ed8df68e4eb661b5a7b915
> #4 CACHED
> 
> #5 [internal] load metadata for docker.io/library/python:3.7
> #5 sha256:2e83735093f2e645c7660e349795ae80186113afc054af8bdc7501e99da12131
> #5 DONE 0.0s
> 
> #6 [build_wheel 1/21] FROM docker.io/library/python:3.7
> #6 sha256:d7e6c383a204ad229f1de34acc46b7a4fa96e4e2006370caf5c4ee33014f7572
> #6 DONE 0.0s
> 
> #7 [internal] load build context
> #7 sha256:dd0ec923c7ff34e475b100538aaddd1b6fc6a0845ad8ae6dcfd6d5466d8e36fe
> #7 transferring context: 48.96kB 0.1s done
> #7 DONE 0.1s
> 
> #8 [stage-1 2/7] COPY tools/install_deps/tensorflow-cpu.txt ./
> #8 sha256:135ef56da15915f1fea5a406d0260b67346b44aadf606da7f989efa60733d71e
> #8 CACHED
> 
> #9 [stage-1 3/7] RUN pip install --default-timeout=1000 --upgrade --force-reinstall -r tensorflow-cpu.txt
> #9 sha256:8ef5ab1c5e90069025ac309475895d00f4b9b541fd6a80317295f2321981433c
> #9 CACHED
> 
> #24 [build_wheel 16/21] RUN python configure.py
> #24 sha256:bf12ca85e9942694bd23e8da117ea97e495067923df62c38b775f8eecdedd1b5
> #24 CACHED
> 
> #20 [build_wheel 12/21] RUN pip install -r pytest.txt pytest-cov
> #20 sha256:06a03b12b7c77cc9bcc404c26038f8653c42642861e994bb46301cc41ac4b79e
> #20 CACHED
> 
> #13 [build_wheel 5/21] COPY tools/docker/install/install_bazel.sh /install/
> #13 sha256:7c51be9cb31e2b947969acc431cff986bbc4e8ef9a925565c6b6d7a07f7af9fc
> #13 CACHED
> 
> #11 [build_wheel 3/21] RUN python -m pip install --upgrade protobuf==3.20.0
> #11 sha256:e03132164318951c06df7514b7a95929387e5178c7aa5395ab245c313a08d9d0
> #11 CACHED
> 
> #23 [build_wheel 15/21] RUN python -m pip install --upgrade protobuf==3.20.0
> #23 sha256:0f1971225c35cb69134598e9fc8c1d83cdb63d7c4fa508fba31102e9149e6920
> #23 CACHED
> 
> #17 [build_wheel 9/21] COPY requirements.txt ./
> #17 sha256:a67c86713993538ceb72172d2120c9cfa34f1e039b36828018dc7049b0876de0
> #17 CACHED
> 
> #19 [build_wheel 11/21] COPY tools/install_deps/pytest.txt ./
> #19 sha256:ae168d1e818c31b4b43d0af4980f329776dca5c943c26782d805bde26bd07aa5
> #19 CACHED
> 
> #21 [build_wheel 13/21] COPY ./ /recommenders-addons
> #21 sha256:59ed814d2cd2bebad2830d17eba71b6fa3d9a038f890e1924dd9b730b2b8590d
> #21 CACHED
> 
> #15 [build_wheel 7/21] COPY tools/docker/install/install_horovod.sh /install/
> #15 sha256:557716a06c281cb44a8b43793d374825a009b5331dda968c1309d8a3925249cc
> #15 CACHED
> 
> #14 [build_wheel 6/21] RUN  /install/install_bazel.sh 5.1.1
> #14 sha256:de2bd374f0f7118287fa1bf3c1ebfad61cf430ef00f664352dfcb694d145213b
> #14 CACHED
> 
> #16 [build_wheel 8/21] RUN  /install/install_horovod.sh 0.23.0 --only-cpu
> #16 sha256:ff0d3f7ddd88cc6fc30c4408a76ef8d49e3e6b67b3f272e69a798d3e6c3e3049
> #16 CACHED
> 
> #12 [build_wheel 4/21] RUN apt-get update && apt-get install -y sudo rsync cmake openmpi-bin libopenmpi-dev
> #12 sha256:e5acfac271796b09ffb6c8783bcc380a5f3a1442abb021b0297d2c4d306d7aa5
> #12 CACHED
> 
> #22 [build_wheel 14/21] WORKDIR recommenders-addons
> #22 sha256:75068cf58e9807f8c74d0ae05f595cb296699fc4dded50a9d793c55f9dedc310
> #22 CACHED
> 
> #18 [build_wheel 10/21] RUN pip install -r requirements.txt
> #18 sha256:a17cb5fab16567fb2238f47aea089ffb0ed71fcc3090b27ad6f1c9a59417541f
> #18 CACHED
> 
> #10 [build_wheel 2/21] RUN pip install --default-timeout=1000 tensorflow-cpu==2.5.1
> #10 sha256:c95cb8cc3d3ef1fde7840d01c58311d00d38527074474c48d31cd380c4f3e992
> #10 CACHED
> 
> #25 [build_wheel 17/21] RUN pip install -e ./
> #25 sha256:09fb1ffeeb84c76581a9ddb0a613fcc9916875bb9b6e4c12df47ebf2e179c8fd
> #25 CACHED
> 
> #26 [build_wheel 18/21] RUN --mount=type=cache,id=cache_bazel,target=/root/.cache/bazel     bash tools/install_so_files.sh
> #26 sha256:25c13fd8882b9cab40f4bba5be6803abfe14cc967ad5faa18d65a3de3cb8f635
> #26 0.237 + bazel build --local_ram_resources=4096 --cxxopt=-w --copt=-w //tensorflow_recommenders_addons/...
> #26 0.293 Starting local Bazel server and connecting to it...
> #26 3.291 Loading:
> #26 3.299 Loading: 0 packages loaded
> #26 4.287 Analyzing: 25 targets (12 packages loaded, 0 targets configured)
> #26 5.315 Analyzing: 25 targets (67 packages loaded, 582 targets configured)
> #26 5.366 WARNING: /root/.cache/bazel/_bazel_root/614b76bd6043cd177ba2f8b6681646ef/external/local_config_tf/BUILD:12657:8: target 'libtensorflow_framework.so.2' is both a rule and a file; please choose another name for the rule
> #26 6.311 Analyzing: 25 targets (77 packages loaded, 8195 targets configured)
> #26 6.734 INFO: Analyzed 25 targets (77 packages loaded, 8309 targets configured).
> #26 6.739 INFO: Found 25 targets...
> #26 6.981 [1 / 7] [Prepa] BazelWorkspaceStatusAction stable-status.txt
> #26 8.312 [14 / 23] checking cached actions
> #26 10.65 [20 / 60] [Prepa] Foreign Cc - CMake: Building hiredis
> #26 12.46 [63 / 112] Foreign Cc - CMake: Building hiredis; 1s local ... (4 actions running)
> #26 13.87 [63 / 112] Foreign Cc - CMake: Building hiredis; 3s local ... (4 actions running)
> #26 18.70 [64 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 7s local ... (4 actions, 3 running)
> #26 21.09 [65 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 9s local ... (4 actions running)
> #26 26.48 [66 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 14s local ... (4 actions, 3 running)
> #26 30.03 [66 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 18s local ... (4 actions running)
> #26 34.07 [67 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 22s local ... (4 actions, 3 running)
> #26 41.49 [68 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 29s local ... (4 actions, 3 running)
> #26 48.53 [68 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 36s local ... (4 actions running)
> #26 55.36 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 43s local ... (4 actions running)
> #26 63.64 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 51s local ... (4 actions running)
> #26 91.24 [69 / 112] Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc; 79s local ... (4 actions running)
> #26 91.37 ERROR: /recommenders-addons/tensorflow_recommenders_addons/dynamic_embedding/core/BUILD:11:18: Compiling tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 48 arguments skipped)
> #26 91.38 gcc: fatal error: Killed signal terminated program cc1plus
> #26 91.38 compilation terminated.
> #26 93.35 INFO: Elapsed time: 92.407s, Critical Path: 84.88s
> #26 93.36 INFO: 12 processes: 5 internal, 7 local.
> #26 93.36 FAILED: Build did NOT complete successfully
> #26 93.46 FAILED: Build did NOT complete successfully
> #26 ERROR: executor failed running [/bin/sh -c bash tools/install_so_files.sh]: exit code: 1
> ------
>  > [build_wheel 18/21] RUN --mount=type=cache,id=cache_bazel,target=/root/.cache/bazel     bash tools/install_so_files.sh:
> ------
> executor failed running [/bin/sh -c bash tools/install_so_files.sh]: exit code: 1
> ```

OK, I see, we have met the same issue, just because the machine has not enough resources ( memory), for resolving it, you can switch to high-performance node for testing, or you can try to limit the resource consumption of Bazel build from here: https://github.com/tensorflow/recommenders-addons/blob/64af57b84ab1b73500d264a5427f65c98c9993a9/tools/docker/cpu_tests.Dockerfile#L39 , like this `bazel build --local_ram_resources=4096`, thank you !

**Comment by rhdong** [comment]
BTW, in your issue description, I found you didn't use the dev container in fact, but anyway it's not the issue's root cause : )

**Comment by GH1995** [comment]
> BTW, in your issue description, I found you didn't use the dev container in fact, but anyway it's not the issue's root cause : )

think you
