### ISSUE TITLE
ROCM toolchain

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/recommenders-addons#274]
**Describe the feature and the current behavior/state.**
Current code base doesn't support build the package on rocm platform, please add rocm toolchain for build the package.
**Relevant information**
- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): yes
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**

**Who will benefit with this feature?**

**Any other info.**

**Comment by rhdong** [comment]
Sorry for the late reply, currently we didn't have enough manpower to support this feature. But if you have the ability to make it we're happy to provide any assistance.

**Comment by MoFHeka** [comment]
A GPU table implementation with ROCM would be helpful.
