### ISSUE TITLE
`de.shadow_ops.embedding_lookup()` is non thread-safe

### ISSUE THREAD

**Issue by alionkun** [tensorflow/recommenders-addons#278]
## Describe the Problem
I built a model based on `de.keras.layers.BasicEmbedding()` and everything worked fine in training phase.
But when serving the trained SavedModel with TFServing, I got two issues:
1. TFServing reported tensor shape mismatch frequently. 
    > error msg: Input to reshape is a tensor with 60 values, but the requested shape has 228 ....
2. TFServing process cored dump occasionally

## Resolving 
After double checking my code and data without any progresses, I dived into the TFRA source code and found following code could bring a race condition:
https://github.com/tensorflow/recommenders-addons/blob/634b96dfd1e9d8722adaeda36b2aa2de61cc65f9/tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py#L219-L251

That is , L250 **updates** `ShadowVariable.ids` (typed `ResourceVariable`)  every time before the real lookup operation,  which is not thread-safe in multi-thread scenario, so are all APIs depending on `de.shadow_ops.embedding_lookup()`.

A similar issue of `DynamiceEmbedding` was fixed at  https://github.com/tensorflow/recommenders-addons/pull/24 , and a quick fixing can be borrowed.

I have solved and verified this issue in my environment and am willing to contribute the fixing. 

@Lifann @rhdong Can you please take a look at this.

**Comment by Lifann** [comment]
Thanks for feedback, @alionkun .  A way to solve this is using `sparse_variable.lookup(keys)` instead of `embedding_lookup(shadow, ids)` in inference phase or exporting the inference model. Maybe it's possible to make it internal.
