### ISSUE TITLE
SavedModel load for tags { serve }; Status: fail: Not found: Op type not registered 'TFRA>CuckooHashTableOfTensors' in binary running on machine.... 

### ISSUE THREAD

**Issue by suzaolin** [tensorflow/recommenders-addons#295]
I had this problem with LoadSavedModel in tensorflow
datail:
Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-12-22 10:53:51.466015: I tensorflow/cc/saved_model/loader.cc:303] SavedModel load for tags { serve }; Status: fail: Not found: Op type not registered 'TFRA>CuckooHashTableOfTensors' in binary running on machine. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.. Took 348271 microseconds.

I use TFRA to train the model, and use LoadSavedModel in tensor flow to load

**Comment by rhdong** [comment]
Hi @suzaolin, could you provide the code that can reproduce it? Thank you!

**Comment by thorneliu** [comment]
It seems that you're serving a TFRA trained model with C++ TF runtime, if so you need to PRELOAD tfra so

**Comment by zyxdtk** [comment]
I face the same problem, when serving model with docker. Is There a tutorials for serving.
Train Model with  TensorFlow 2.8.3, TFRA  0.5.0
Serving with  tensorflow/serving:2.5.2
Detail:
I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: fail: Not found: Op type not registered 'TFRA>CuckooHashTableOfTensors' in binary running on 7dcde1ba51d1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.. Took 19251 microseconds.

**Comment by rhdong** [comment]
> I face the same problem, when serving model with docker. Is There a tutorials for serving. Train Model with TensorFlow 2.8.3, TFRA 0.5.0 Serving with tensorflow/serving:2.5.2 Detail: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: fail: Not found: Op type not registered 'TFRA>CuckooHashTableOfTensors' in binary running on 7dcde1ba51d1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.. Took 19251 microseconds.

Hi @zyxdtk , thank you for your feedback! This issue is duplicate with another resolved one that has been resolved. Please refer to it : https://github.com/tensorflow/recommenders-addons/issues/296#issuecomment-1371772559 .
