### ISSUE TITLE
Can some documentation be provided on how to build the TensorFlow C++ library from source to use TFRA custom ops in the TensorFlow C++ API?

### ISSUE THREAD

**Issue by WangShengguang** [tensorflow/recommenders-addons#296]
We use TFRA for offline training, and the online service uses rpc + Tensorflow dynamic link library.

I encountered some problems during the joint compilation phase of TFRA and TF. I tried to compile it referring to this link, but was unsuccessful: https://github.com/tensorflow/recommenders-addons/issues/103. 

Can some documentation be provided on how to build the TensorFlow C++ library from source to use TFRA custom ops in the TensorFlow C++ API?

**Comment by rhdong** [comment]
Hi @WangShengguang, thank you for your feedback! Please refer to the comment: https://github.com/tensorflow/recommenders-addons/issues/103#issuecomment-867606225

**Comment by thorneliu** [comment]
You may try:
```
./configure
bazel build -c opt --config=numa --copt="-O3" //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //tensorflow:install_headers
```

Then install the *.so and headers in /usr/local/

To use TFRA custom ops, just preload the TFRA so:
```
LD_PRELOAD="/usr/local/lib/_cuckoo_hashtable_ops.so /usr/local/lib/_math_ops.so" ./your_app
```

**Comment by rhdong** [comment]
> You may try:
> 
> ```
> ./configure
> bazel build -c opt --config=numa --copt="-O3" //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //tensorflow:install_headers
> ```
> 
> Then install the *.so and headers in /usr/local/
> 
> To use TFRA custom ops, just preload the TFRA so:
> 
> ```
> LD_PRELOAD="/usr/local/lib/_cuckoo_hashtable_ops.so /usr/local/lib/_math_ops.so" ./your_app
> ```

Hi @WangShengguang, could you please help check if this solution works for you? Thank you!

**Comment by WangShengguang** [comment]
> > You may try:
> > ```
> > ./configure
> > bazel build -c opt --config=numa --copt="-O3" //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //tensorflow:install_headers
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then install the *.so and headers in /usr/local/
> > To use TFRA custom ops, just preload the TFRA so:
> > ```
> > LD_PRELOAD="/usr/local/lib/_cuckoo_hashtable_ops.so /usr/local/lib/_math_ops.so" ./your_app
> > ```
> 
> Hi @WangShengguang, could you please help check if this solution works for you? Thank you!

@thorneliu @WangShengguang  Thanks for answering my question. But there are some new things recently, it may take a few days.

**Comment by rhdong** [comment]
> > > You may try:
> > > ```
> > > ./configure
> > > bazel build -c opt --config=numa --copt="-O3" //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //tensorflow:install_headers
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then install the *.so and headers in /usr/local/
> > > To use TFRA custom ops, just preload the TFRA so:
> > > ```
> > > LD_PRELOAD="/usr/local/lib/_cuckoo_hashtable_ops.so /usr/local/lib/_math_ops.so" ./your_app
> > > ```
> > 
> > 
> > Hi @WangShengguang, could you please help check if this solution works for you? Thank you!
> 
> @thorneliu @rhdong Thanks for answering my question. But there are some new things recently, it may take a few days.

Hi @WangShengguang, is there any update? :)

**Comment by rhdong** [comment]
Hi @WangShengguang , we are relatively sure that the solution from @thorneliu can solve the issue. We will close this issue first. If any problem please feel free to reopen it, thank you for your feedback!
