### ISSUE TITLE
GPU and CPU inference are inconsistent

### ISSUE THREAD

**Issue by UnknownSwordsman** [tensorflow/recommenders-addons#324]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos
- TensorFlow version and how it was installed (source or binary): 2.8.3, pip install
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): 0.5.1
- Python version:  3.7.16
- Is GPU used? (yes/no): yes

**Describe the bug**

When using the Keras model  for inference, the results of GPU and CPU inference are inconsistent
This model train on gpu, and the graph rebuild by de.enable_inference_mode().

![image](https://user-images.githubusercontent.com/32473574/230867872-a7aeb2ce-a5d5-4ede-b131-7b700f053cd0.png)

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

import os;os.environ['CUDA_VISIBLE_DEVICES'] = '-1' 
import tensorflow as tf
import tensorflow_recommenders_addons.dynamic_embedding as de

func = tf.saved_model.load('model_path').signatures['serving_default']
func(**tensors)

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/32473574/230869080-93d707b3-2067-4bd8-b874-9ef20dc83056.png)

**Comment by MoFHeka** [comment]
I'm not sure if this is a problem caused by TFRA, as even the TF itself can have issues with inconsistent CPU and GPU inference results.
