### ISSUE TITLE
the issure of SquashedEmbedding output

### ISSUE THREAD

**Issue by andrew-zzz** [tensorflow/recommenders-addons#332]
**System information**
- Linux version 3.10.0
- TensorFlow version 2.8.3,binary
- TensorFlow-Recommenders-Addons version 0.6 binary
- Python version:3.8
- Is GPU used? (yes/no):no

**Describe the bug**
i define SquashedEmbedding and input the same value but output is always different ,in my opinion,the same index's embedding value should be the same

**Code to reproduce the issue**

import tensorflow as tf
from tensorflow_recommenders_addons import dynamic_embedding as de
embedding123 = de.keras.layers.SquashedEmbedding(8) # embedding size 8

ids = tf.constant([2], dtype=tf.int64) # (5,)
out = embedding123(ids) # (8,)
print(out)

ids = tf.constant([2], dtype=tf.int64) # (5,)
out = embedding123(ids) # (8,)
print(out)

**Other info / logs**

tf.Tensor(
[ 0.05978089  0.03316572 -0.07647184  0.00869708 -0.00297723  0.06943578
  0.04013071  0.07524309], shape=(8,), dtype=float32)
tf.Tensor(
[ 0.01806082 -0.01919503 -0.00533127  0.00594071 -0.04968594 -0.0423859
 -0.01083221  0.01112545], shape=(8,), dtype=float32)

**Comment by rhdong** [comment]
Hi @andrew-zzz . thank you for your feedback. According to your code, I believe it's normal because the embedding parameters will be updated only in backpropagation.

**Comment by andrew-zzz** [comment]
the initialization  the random
