### ISSUE TITLE
does recommenders-addons support bare tf c++ api inference?

### ISSUE THREAD

**Issue by xiedeacc** [tensorflow/recommenders-addons#344]
out inference server was written use TF c++ api directly, can it possible to import recommenders-addons? if possible, hope give same procedure, thanks

**Comment by thorneliu** [comment]
Hi,

The answer is yes. Please refer to closed issue https://github.com/tensorflow/recommenders-addons/issues/296

BR

**Comment by xiedeacc** [comment]
thanks
