### ISSUE TITLE
TFRA load embedding weights with wrong value when use CPU table

### ISSUE THREAD

**Issue by fuhailin** [tensorflow/recommenders-addons#363]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu20.04
- TensorFlow version and how it was installed (source or binary): binary
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): source
- Python version: 3.9
- Is GPU used? (yes/no): yes

**Describe the bug**
TFRA load embedding weights with wrong value when use CPU table

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by MoFHeka** [comment]
Fixed in #364
