### ISSUE TITLE
Support for Python 3.10?

### ISSUE THREAD

**Issue by philipkd** [tensorflow/recommenders-addons#369]
I'm trying to run the [dynamic embedding tutorial](https://github.com/tensorflow/recommenders-addons/blob/master/demo/dynamic_embedding/movielens-1m-keras-notebook/movielens_dynamic_embedding_tutorial.ipynb) on Colab, but Python 3.9 is no longer supported, which is the latest version that TFRA is built against. Is there any way to get an updated PyPI release?

**Relevant information**

- Are you willing to contribute it (yes/no): yes
- Are you willing to maintain it going forward? (yes/no): no

**Who will benefit with this feature?**

Anybody trying to follow this [TensorFlow blog on training a recommender system](https://blog.tensorflow.org/2023/04/training-recommendation-model-with-dynamic-embeddings.html).

**Comment by MoFHeka** [comment]
Python 3.10 is compatible. You could build TFRA by yourself or just wait some time.

**Comment by alykhantejani** [comment]
This can be closed I think as 0.7.0 is now out
