### ISSUE TITLE
support ragged tensor or input with mask for SquashedEmbedding

### ISSUE THREAD

**Issue by lu-sitong** [tensorflow/recommenders-addons#380]
I notice that SquashedEmbedding allow arbirary shape of tensor and reduce them after lookup.
But in most situations, inputs may  be ragged tensors, like tags and other sideinfos.
In this case, i try to convert ragged tensors to regular tensors with mask.
I find  SquashedEmbedding indeed doesn't support mask, even thought api_docs shows SquashedEmbedding has a method 'compute_mask()'. I cannot find this method in source code.
Expect to support ragged tensor input or regular  tensor input with mask for SquashedEmbedding class

**Comment by MoFHeka** [comment]
Sorry that we haven't started to code this function. If possible, could you please contribute the corresponding code?
