### ISSUE TITLE
inference mode issue

### ISSUE THREAD

**Issue by beijinggao** [tensorflow/recommenders-addons#390]
**After exporting the model for prediction, I found that setting de.enable_inference_mode() is required.** 

and comment is :
**de.enable_inference_mode()**

TrainableWrapper.read_value` is not thread-safe that causes threads
competition and Out-Of-Bound exception in concurrent serving scenario.

To resolve this, we define the `ModelMode` APIs to instruct
the `TrainableWrapper` to build a different thread-safe sub-graph
for 'TrainableWrapper.read_value' on inference mode.

**But after export the model and use tensorflow serving or trion to inference，how to set enable_inference_mode()，or is it necessary ?**

**Comment by MoFHeka** [comment]
```python
model = build_model(xxx)
de.enable_inference_mode()
model.save(export_dir)
```

enable_inference_mode is used to change the graph building logic inner TFRA. It would be reduce two times memory copy in TrainableWrapper which are IDs and Embedding Values.

**Comment by MoFHeka** [comment]
@beijinggao Do you have any questions? If not, I will close the issue.

**Comment by liyuan97** [comment]
model = build_model(xxx)
de.enable_inference_mode()
model.save(export_dir)


这样保存了，但是推理的时候还是用了两倍内存，是不是推理 load 模型的时候也得怎么设置一下？ @MoFHeka

**Comment by MoFHeka** [comment]
看一下embedding的init size、init capacity是否过大。推理构造模型的时候别构造优化器、或用tf.savemodel.load加载、或把优化器参数直接目录内移除。

**Comment by liyuan97** [comment]
优化器是已经删了，现在模型文件 10G，serving load 之后需要 20G 左右。不知道是不是还有问题

**Comment by MoFHeka** [comment]
试一下LD_PRELOAD jemalloc，可能内存利用效率有点问题。
