### ISSUE TITLE
栈溢出风险

### ISSUE THREAD

**Issue by dropdust** [tensorflow/recommenders-addons#405]
https://github.com/tensorflow/recommenders-addons/blob/53b5ac89acddf9e96902e98946e6a8d94589dd02/tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp#L73

Linux系统文件路径可能超过1024 字节，存在栈溢出风险。

**Comment by rhdong** [comment]
Hi @MoFHeka , could you help with it? Many thanks!

**Comment by MoFHeka** [comment]
@rhdong Fixed with PR #415
