### ISSUE TITLE
_math_ops.so: undefined symbol

### ISSUE THREAD

**Issue by hauturier** [tensorflow/recommenders-addons#406]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow version and how it was installed (source or binary): 2.14.0
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): tfra-nightly-gpu
- Python version: 3.11.3
- Is GPU used? (yes/no): yes

**Describe the bug**

when import tfra package, problem raises:

python3.11/site-packages/tensorflow_recommenders_addons/dynamic_embedding/core/_math_ops.so: undefined symbol: _ZN4absl12lts_2023012512log_internal15LogMessageFatalC1EPKciSt17basic_string_viewIcSt11char_traitsIcEE

And any plan for next release, e.g.: 0.6.1?

**Comment by rhdong** [comment]
Hi @hauturier, could you provide a simple python demo for reproducing it?

**Comment by hauturier** [comment]
I tried to install tfra wheel package of latest official version and there's no problem, thanks.
