### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by alykhantejani** [tensorflow/recommenders-addons#414]
Hi, 

I was wondering if a new version will be cut anytime soon, I see there are many changes since a year ago.

I recently hit an error:
```
data.shape must start with partitions.shape, got data.shape = [2,64], partitions.shape = [1]\n\t [[{{node SGD/SGD/update_21/DynamicPartition_2}}]]
```

Which comes from the `DynamicEmbeddingOptimizer` trying to partition the data. I see in master you no longer use `tf. dynamic_partition` and use `tfra_data_flow_ops.tfra_dynamic_partition` which might solve it?

**Comment by rhdong** [comment]
Hey @alykhantejani, thank you for connecting with us. The new version should be available very soon. We noticed the `dynamic_partition` issue and are working on it. We will get back to you when we get a point. Many thanks!

**Comment by alykhantejani** [comment]
@rhdong ok thanks, so is still an issue in master?

**Comment by MoFHeka** [comment]
> Hi,
> 
> I was wondering if a new version will be cut anytime soon, I see there are many changes since a year ago.
> 
> I recently hit an error:
> 
> ```
> data.shape must start with partitions.shape, got data.shape = [2,64], partitions.shape = [1]\n\t [[{{node SGD/SGD/update_21/DynamicPartition_2}}]]
> ```
> 
> Which comes from the `DynamicEmbeddingOptimizer` trying to partition the data. I see in master you no longer use `tf. dynamic_partition` and use `tfra_data_flow_ops.tfra_dynamic_partition` which might solve it?

tfra_data_flow_ops.tfra_dynamic_partition is mostly same as tf.dynamic_partition except supporting additional input type. So you may pass an illegal parameter into tf.dynamic_partition OP.

**Comment by alykhantejani** [comment]
Ok so this probably isnt going to solve my issue. @rhdong you said you noticed the dynamic partition issue? Is this a known bug, perhaps you could shed more light on to what the problem is?

**Comment by alykhantejani** [comment]
Closing as 0.7.0 is released
