### ISSUE TITLE
Is there a TFRA package that  is compatible with TensorFlow 1.x?

### ISSUE THREAD

**Issue by amznero** [tensorflow/recommenders-addons#42]
Hi,
I found that TFRA only supports TF 2.4.1 for now, but I often use TF 1.x in my code.

I want to confirm if there are any plans to release a TF1.x-Compatible package?

**Comment by rhdong** [comment]
Hi @amznero, if you need to work with other versions of TensorFlow, we recommend you installing from source by follow the guide on home page.

**Comment by amznero** [comment]
Hi, 

I got some error messages when I use Bazel to build TFRA. 

It seems like there is no `lookup_util.h` file in my TensorFlow packages.

---

failed command

`bazel build --enable_runfiles build_pip_pkg` 

---

Build log:
```text
Starting local Bazel server and connecting to it...
WARNING: /home/jovyan/.cache/bazel/_bazel_jovyan/9656d07a7182332e1e30eaea9fdcde12/external/local_config_tf/BUILD:4889:1: target 'libtensorflow_framework.so.1' is both a rule and a file; please choose another name for the rule
INFO: Analyzed target //:build_pip_pkg (29 packages loaded, 146 targets configured).
INFO: Found 1 target...
ERROR: /home/jovyan/codes/recommenders-addons/tensorflow_recommenders_addons/dynamic_embedding/core/BUILD:7:1: C++ compilation of rule '//tensorflow_recommenders_addons/dynamic_embedding/core:_cuckoo_hashtable_ops.so' failed (Exit 1)
In file included from tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc:18:0:
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.h:25:49: fatal error: tensorflow/core/kernels/lookup_util.h: No such file or directory
 #include "tensorflow/core/kernels/lookup_util.h"
                                                 ^
compilation terminated.
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.982s, Critical Path: 7.11s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully
````

---

Environment:

Ubuntu 18.04
TensorFlow: 1.15
Bazel: 3.1

---

ps. It seems like this repo only supports Bazel v3.1 to build packages. (setting in recommenders-addons/.bazelversion)

**Comment by rhdong** [comment]
Hi @amznero , can you execute `python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'` and check the file in the tensorflow_core/include ?

**Comment by amznero** [comment]
Hi @rhdong, sorry for the late reply.

I have tried to build it in tf1.15 and tf2.4.

## TF 1.15 ENV

After I execute the above command, I got `-I/home/nero/miniconda3/envs/myenv/lib/python3.7/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0`.

And I listed that dir
```bash
>> ls /home/nero/miniconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/include/tensorflow/core/
>>     common_runtime/ example/        framework/      graph/          grappler/       lib/            platform/       protobuf/       public/         util/
```

It seems like there is no `kernel` dir in it.

I have tried to install tensorflow==1.15 from PyPI or Conda, they have both failed with the same error message.

---

## TF 2.x ENV

I compiled it successfully when the tensorflow==2.4.

```bash
>> python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))'
>>   -I/home/nero/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0
>>

>> ls /home/nero/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/
>>   common_runtime/      distributed_runtime/ graph/               lib/                 profiler/            summary/             
>>   data/                example/             grappler/            nccl/                protobuf/            tpu/                 
>>   debug/               framework/           kernels/             platform/            public/              util/
```
---

The include dir and the content inside are different between tf1.x and tf2.x. Is this the reason why I can't compile TFRA?

**Comment by rhdong** [comment]
Hi @amznero , I have make a personal branch for compiling with tf1.15.2 version ,and there are some work to do for merge to master, before that you can use this branch to try TFRA. The next version will be released before May 10th that will be compatible with TF1.x and well tested.

[https://github.com/rhdong/recommenders-addons/tree/rhdong/compile-with-tf1152](https://github.com/rhdong/recommenders-addons/tree/rhdong/compile-with-tf1152)

**Comment by amznero** [comment]
@rhdong  Thanks! I will try it as soon as possible.

**Comment by amznero** [comment]
I successfully built TFRA using branch-compile-with-tf1152 and got the wheel.

However, some errors occurred when importing TFRA.

```python
import tensorflow_recommenders_addons as tfra
```
```bash
NotFoundError: /home/jovyan/codes/rhdong_tfra/tensorflow_recommenders_addons/dynamic_embedding/core/_cuckoo_hashtable_ops.so: cannot open shared object file: No such file or directory
```

And I checked the dir `tensorflow_recommenders_addons/dynamic_embedding/core`, got this
```bash
ls /home/jovyan/codes/rhdong_tfra/tensorflow_recommenders_addons/dynamic_embedding/core/

BUILD  kernels  lib  ops
```
