### ISSUE TITLE
pip install wrong

### ISSUE THREAD

**Issue by weizaixl** [tensorflow/recommenders-addons#49]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): pip install tensorflow-recommenders-addons[tensorflow]
- TensorFlow-Recommenders-Addons version and how it was installed (source or binary): binary 
- Python version: 3.7.9
- Is GPU used? (yes/no): yes

**Describe the bug**

**Code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I have installed recommenders-addons via "pip install tensorflow-recommenders-addons[tensorflow]"> However, it tells me the versions don't match.

![image](https://user-images.githubusercontent.com/23149296/114962865-1c321e00-9e9e-11eb-83ff-714ba0b55be7.png)

**Comment by rhdong** [comment]
Hi @weizaixl ，thank for your feedback and I'm sorry for late reply.
Plz install TFRA by executing `pip install tensorflow-recommenders-addons` and the current release of TFRA is still not compatible with TF GPU version. But we plan to publish recently a new release supporting GPU version.

**Comment by rhdong** [comment]
Hi @weizaixl, I fixed it and just a wrong warning, you can ignore it before next release.

**Comment by rhdong** [comment]
I move this issue to closed status as its resolve.
