### ISSUE TITLE
Can I have an example of distributed training

### ISSUE THREAD

**Issue by somelaoda** [tensorflow/recommenders-addons#56]
Now I'm honored to run through 2 examples at
 https://github.com/tensorflow/recommenders-addons/tree/master/docs/tutorials
,but all of those ipynb are training at localhost.

I hope official can provide a distributed training exapmle（use 
recommenders-addons）on tensorflow2.4.

The use of parameter-server training in Tensorflow2 does not seem to be tensorflow officially encouraged, and I have no experience with it.
thank you very much.

**Comment by rhdong** [comment]
Hi @somelaoda, we provide a distributed demo with estimator: https://github.com/tensorflow/recommenders-addons/tree/master/demo/movielens-100k-estimator

**Comment by rhdong** [comment]
This issue will be closed for resolved in [TFRA 0.2.0](https://github.com/tensorflow/recommenders-addons/releases/tag/v0.2.0), you can reopen it for free if any questions, thanks !
