### ISSUE TITLE
Add Support for Apple Silicon (M1)

### ISSUE THREAD

**Issue by poinwater** [tensorflow/recommenders-addons#59]
**Hardware info**
Machine: MacBook Air
OS: macOS BigSur 11.2.3
Chip: Apple M1 (8cpu, 8gpu)
RAM: 16GB

**Software info**
Python:3.8
PIP: 21.0.1
Miniforge: 4.10.1
Tensorflow-macos: 2.4.0-rc0 (0.1a3)
Bazel: 4.0.0-homebrew
Homebrew: 3.1.3

**Description**
I couldn't use `pip install tensorflow-recommenders-addons` to install the addon on my system, I tried Rosseta x86 terminal, but the 2.4.1 tensorflow can't run in Rosseta. So I tried to compile the source code by Bazel.

To compile the Apple Silicon version, I changed:
./.bazelversion
from `3.1.0`
to     `4.0.0`

./build_deps/build_pip_pkg.sh
from
`BUILD_CMD="${BUILD_CMD} --plat-name macosx_10_13_x86_64"`
to
`BUILD_CMD="${BUILD_CMD} --plat-name macosx_11_0_arm64`

./requirement.txt
delete `tensorflow=2.4.1`

./tensorflow_recommenders_addons/version.py
from 
`MIN_TF_VERSION = "2.4.1"`
`MAX_TF_VERSION = "2.4.1"`
to
`MIN_TF_VERSION = "2.4.0-rc0"`
`MAX_TF_VERSION = "2.4.0-rc0"`

**Compiling Process**
```
git clone https://github.com/tensorflow/recommenders-addons.git
cd recommenders-addons

# This script links project with TensorFlow dependency
python3 ./configure.py

bazel build --enable_runfiles build_pip_pkg
bazel-bin/build_pip_pkg artifacts

pip install artifacts/tensorflow_recommenders_addons-*.whl
```

Here is the wheel file:
[tensorflow_recommenders_addons-0.0.1.dev0-cp38-cp38-macosx_11_0_arm64.whl](https://github.com/poinwater/recommenders-addons/releases/download/0.1.0-m1/tensorflow_recommenders_addons-0.0.1.dev0-cp38-cp38-macosx_11_0_arm64.whl)

The Forked Repo:
[tf-recommender-m1](https://github.com/poinwater/recommenders-addons/tree/tf-recommender-addons-m1)
[Release Page](https://github.com/poinwater/recommenders-addons/releases/tag/0.1.0-m1)  

**Current issue**
I still get some warning messages while running the tutorial ipynb file.
The dynamic_embedding_tutorial.ipynb works properly except for some warning messages, but the embedding_variable_tutorial.ipynb raises an error as follows:
`InvalidArgumentError: type of indices is not match with EmbeddingVariable key type.`
I also tried to use Colab to run the embedding_variable_tutorial.ipynb, and I got the same error. I think it might not be my problem.

**Comment by rhdong** [comment]
@candyzone

**Comment by rhdong** [comment]
Hi @poinwater , thank for your feeadback. We have not officially supported m1 yet, but we will incorporate it into the development plan based on demand.  And I suggest you pull another issue for the `EmbeddingVariable` exception.

**Comment by rhdong** [comment]
I will close this issue, anyone want to run TFRA on MacOS with M1 plz reference to the .
