### ISSUE TITLE
source build detail tutorial

### ISSUE THREAD

**Issue by wjzhello** [tensorflow/recommenders-addons#64]
**1  build tfra** 
build other version tensorflow the tfra need update follow file.
1.1 requirements.txt
1.2 tensorflow_recommenders_addons/version.py:MIN_TF_VERSION, tensorflow_recommenders_addons/version.py:MAX_TF_VERSION

**2 build tf-serving with tfra**
2.1 git clone https://github.com/tensorflow/recommenders-addons.git 
2.2 git clone -b r2.4 https://github.com/tensorflow/serving.git 
2.3 cp -r recommenders-addons/tensorflow_recommenders_addons serving/
      cp -r recommenders-addons/build_deps  serving/
2.4 pip install tensorflow==**{version}**
2.5 cd recommenders-addons/  
     python recommenders-addons/configure.py
     cat .bazelrc >> ../serving/.bazelrc
     cat WORKSPACE >> ../serving/WORKSPACE
     vim ../serving/WORKSPACE | and delete workspace(name = "tf_recommenders_addons")
     update  tensorflow_recommenders_addons/tensorflow_recommenders_addons.bzl
     
![屏幕快照 2021-04-28 下午3 38 21](https://user-images.githubusercontent.com/83278232/116365948-599c9100-a838-11eb-831d-1b29b1f89231.png)

     cd ../
2.6 cd serving
     update tensorflow_serving/model_servers/BUILD
![屏幕快照 2021-04-28 下午3 49 48](https://user-images.githubusercontent.com/83278232/116367025-7be2de80-a839-11eb-95a3-03c6acdfb2e4.png)
   cd ../
2.7 install docker
2.8 upgrade gcc,g++
2.9 cd serving/
  tools/run_in_docker.sh bazel build tensorflow_serving/model_servers:tensorflow_model_server
  need about four hours building.
2.10 test
tools/run_in_docker.sh -o "-p 8501:8501" \
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server \
--rest_api_port=8501 --model_name=<model_name> --model_base_path=<model_base_path>

**Comment by rhdong** [comment]
Hi @Mr-Nineteen , can you help? Thanks~

**Comment by Mr-Nineteen** [comment]
@wjzhello  The test method is correct, are you trying to record it?

**Comment by Mr-Nineteen** [comment]
**Especially need to pay attention to:**
native.**cc_library**(
        name = name,
        srcs = srcs,
        copts = copts,
        **alwayslink** = 1,
        features = select({
            "//tensorflow_recommenders_addons:windows": ["windows_export_all_symbols"],
            "//conditions:default": [],
        }),
        deps = deps,
        **kwargs
    )
