### ISSUE TITLE
_VALID_BAZEL_VERSION  also use 3.1.0 for tf 1.15.2?

### ISSUE THREAD

**Issue by ideafold** [tensorflow/recommenders-addons#98]
https://github.com/tensorflow/recommenders-addons/blob/9257222cda9115148e840958e0bff4c147bd53b7/configure.py#L28

when tf + tfra is 1.15.2, bazel 3.1.0 also works ?
i had compiled with bazel 3.1.0 successfully.

**Comment by rhdong** [comment]
Yes, It works to compile 1152 with bazel 310 or 0261, but official release
used config in  _valide_bazle_version
